### ISSUE TITLE
Adding options after votes have been registered

### ISSUE THREAD

**Issue by matzekuh** [matzekuh/dokuwiki-plugin-doodle3#5]
When adding options after users have given their votes there appears a problem that seems difficult to fix.
Options can only be added in the last position, when adding options in front or between the other positions answers wont move with the options.

With good instruction of all users you wont be affected by this bug.

**Comment by yanosz** [comment]
We've just ran into this issue on a small planning site. One author had a long running doodle, new options were added continuously. There was no error-message or warning.

Can you outline, why this is "wontfix". Persisting option-names instead of numbers, seems to be reasonable. This can also be extended by save an optional description to detect changes in options. 

```php
Sabine' => array(
            'choices'   => array('option_rainbow_dash', 'option_pinkie_pie'), // array(0, 1, 2, 3, 4), 
            'ip'        => '333.333.333.333',
            'time'      => 1284970222
          ),
```

**Comment by matzekuh** [comment]
I absolutely agree, that this would improve the plugin.
The thing is, that on our own wiki we do not need this feature as the plugin worked well for us in the past without changing this behaviour. As a result, I can't take the time to do the programming at the moment as well as in the near future.

**Comment by yanosz** [comment]
Thanks for your feedback.

I checked the source code to see if it's doable. On the one hand, it looks doable, on the other I'm somewhat afraid to break something: `render( )` has > 200 lines and I didn't find any automated tests. Do you have a test instance? Did miss something?

**Comment by yanosz** [comment]
I started playing around: https://github.com/yanosz/dokuwiki-plugin-doodle3/tree/feature/options-by-name

We didn't do integration testing, yet. Also, I assumed, that comment on the data structure is up-to-date. Tests are green (https://github.com/yanosz/dokuwiki-plugin-doodle3/blob/feature/options-by-name/test_non_numeric_choices.php).
